import type { ManufacturingGenerationConfig } from "./types";

/** 完整制造目录的确定性数据源与数值规则。 */
export const MANUFACTURING_GENERATION_CONFIG = {
  cityIds: [
    "city_a",
    "city_b",
    "city_c",
    "city_d",
    "city_e",
    "city_f",
    "city_g",
    "city_h",
  ],
  districtCodes: ["A", "B", "C", "D", "E", "F"],
  blueprintSourceOffset: 17,
  recipeSourceOffset: 0,
  blueprintResearchCoinBase: 12,
  blueprintResearchPartsBase: 8,
  blueprintResearchDaysBase: 1,
  grades: [
    { gradeId: "rough", displayPrefix: "粗制", costMultiplierPercent: 70, durationDays: 1, rarity: 1 },
    { gradeId: "standard", displayPrefix: "制式", costMultiplierPercent: 85, durationDays: 1, rarity: 2 },
    { gradeId: "reinforced", displayPrefix: "加固", costMultiplierPercent: 100, durationDays: 1, rarity: 3 },
    { gradeId: "industrial", displayPrefix: "工业", costMultiplierPercent: 120, durationDays: 1, rarity: 4 },
    { gradeId: "precision", displayPrefix: "精密", costMultiplierPercent: 145, durationDays: 2, rarity: 5 },
    { gradeId: "tactical", displayPrefix: "战术", costMultiplierPercent: 175, durationDays: 2, rarity: 6 },
    { gradeId: "expert", displayPrefix: "专家", costMultiplierPercent: 210, durationDays: 2, rarity: 7 },
    { gradeId: "military", displayPrefix: "军规", costMultiplierPercent: 250, durationDays: 3, rarity: 8 },
    { gradeId: "pioneer", displayPrefix: "先驱", costMultiplierPercent: 300, durationDays: 3, rarity: 9 },
    { gradeId: "legacy", displayPrefix: "传承", costMultiplierPercent: 360, durationDays: 4, rarity: 10 },
  ],
  basicFamilies: [
    {
      familyId: "wild_tuber",
      displayName: "野生块茎",
      description: "筛去腐烂部分的高淀粉块茎，需充分煮熟。",
      category: "raw_food",
      tags: ["food", "raw", "plant"],
      baseCoinCost: 1,
      basePartsCost: 0,
      baseBarterCost: 1,
      barterItemId: "clean_water",
      barterItemName: "洁净水",
      outputQuantity: 3,
    },
    {
      familyId: "forest_mushroom",
      displayName: "林地菌筐",
      description: "经过孢子特征筛选的可食用菌类，仍不宜生食。",
      category: "raw_food",
      tags: ["food", "raw", "fungus"],
      baseCoinCost: 1,
      basePartsCost: 0,
      baseBarterCost: 1,
      barterItemId: "salt_packet",
      barterItemName: "盐包",
      outputQuantity: 3,
    },
    {
      familyId: "freshwater_fish",
      displayName: "淡水鱼",
      description: "从城市河道上游捕获的鲜鱼，需去除寄生虫风险。",
      category: "raw_food",
      tags: ["food", "raw", "fish"],
      baseCoinCost: 2,
      basePartsCost: 0,
      baseBarterCost: 1,
      barterItemId: "fishing_hook",
      barterItemName: "鱼钩",
      outputQuantity: 2,
    },
    {
      familyId: "poultry_meat",
      displayName: "禽肉",
      description: "幸存者饲养点交换来的生禽肉，需高温处理。",
      category: "raw_food",
      tags: ["food", "raw", "meat"],
      baseCoinCost: 2,
      basePartsCost: 0,
      baseBarterCost: 1,
      barterItemId: "grain_sack",
      barterItemName: "谷物袋",
      outputQuantity: 2,
    },
    {
      familyId: "venison_cut",
      displayName: "猎物肉块",
      description: "从城郊猎物分割的肉块，污染情况尚未确定。",
      category: "raw_food",
      tags: ["food", "raw", "meat"],
      baseCoinCost: 3,
      basePartsCost: 0,
      baseBarterCost: 1,
      barterItemId: "cloth_roll",
      barterItemName: "布卷",
      outputQuantity: 2,
    },
    {
      familyId: "salvaged_grain",
      displayName: "筛选谷物",
      description: "从破损粮仓中筛出的可用谷粒，是多种半成品的原料。",
      category: "raw_food",
      tags: ["food", "raw", "grain"],
      baseCoinCost: 1,
      basePartsCost: 0,
      baseBarterCost: 1,
      barterItemId: "paper_bundle",
      barterItemName: "纸束",
      outputQuantity: 4,
    },
    {
      familyId: "clean_water",
      displayName: "净化水",
      description: "经过沉淀、过滤与煮沸的半成品饮用水。",
      category: "semi_finished_food",
      tags: ["food", "semi_finished", "water"],
      baseCoinCost: 1,
      basePartsCost: 1,
      baseBarterCost: 0,
      barterItemId: "none",
      barterItemName: "无",
      outputQuantity: 4,
    },
    {
      familyId: "dried_meat",
      displayName: "脱水肉条",
      description: "用盐和烟熏处理的耐储肉类半成品。",
      category: "semi_finished_food",
      tags: ["food", "semi_finished", "meat"],
      baseCoinCost: 2,
      basePartsCost: 1,
      baseBarterCost: 1,
      barterItemId: "salt_packet",
      barterItemName: "盐包",
      outputQuantity: 2,
    },
    {
      familyId: "grain_flour",
      displayName: "混合粗粮粉",
      description: "研磨后可用于面饼和糊粥的稳定半成品。",
      category: "semi_finished_food",
      tags: ["food", "semi_finished", "grain"],
      baseCoinCost: 1,
      basePartsCost: 1,
      baseBarterCost: 1,
      barterItemId: "salvaged_grain",
      barterItemName: "筛选谷物",
      outputQuantity: 3,
    },
    {
      familyId: "pickled_vegetable",
      displayName: "盐渍蔬菜",
      description: "发酵后可长期保存的半成品蔬菜。",
      category: "semi_finished_food",
      tags: ["food", "semi_finished", "vegetable"],
      baseCoinCost: 2,
      basePartsCost: 1,
      baseBarterCost: 1,
      barterItemId: "glass_jar",
      barterItemName: "玻璃罐",
      outputQuantity: 3,
    },
    {
      familyId: "broth_base",
      displayName: "高汤底料",
      description: "由骨料、根茎与盐熬制的烹饪半成品。",
      category: "semi_finished_food",
      tags: ["food", "semi_finished", "broth"],
      baseCoinCost: 2,
      basePartsCost: 1,
      baseBarterCost: 1,
      barterItemId: "fuel_briquette",
      barterItemName: "燃料块",
      outputQuantity: 2,
    },
    {
      familyId: "cooking_oil",
      displayName: "粗滤食用油",
      description: "从油料作物中压榨并粗滤的烹饪半成品。",
      category: "semi_finished_food",
      tags: ["food", "semi_finished", "oil"],
      baseCoinCost: 2,
      basePartsCost: 1,
      baseBarterCost: 1,
      barterItemId: "filter_cloth",
      barterItemName: "滤布",
      outputQuantity: 2,
    },
    {
      familyId: "sterile_bandage",
      displayName: "无菌绷带",
      description: "消毒、密封后用于处理开放伤口。",
      category: "medicine",
      tags: ["medical", "consumable"],
      baseCoinCost: 2,
      basePartsCost: 1,
      baseBarterCost: 1,
      barterItemId: "cloth_roll",
      barterItemName: "布卷",
      outputQuantity: 2,
    },
    {
      familyId: "disinfectant",
      displayName: "消毒液",
      description: "用于器械、伤口边缘和台面的基础消毒剂。",
      category: "medicine",
      tags: ["medical", "consumable"],
      baseCoinCost: 3,
      basePartsCost: 1,
      baseBarterCost: 1,
      barterItemId: "alcohol_bottle",
      barterItemName: "酒精瓶",
      outputQuantity: 2,
    },
    {
      familyId: "fastener_set",
      displayName: "紧固件组",
      description: "经清理和分类的螺栓、螺母与垫片。",
      category: "material",
      tags: ["crafting", "metal"],
      baseCoinCost: 1,
      basePartsCost: 2,
      baseBarterCost: 0,
      barterItemId: "none",
      barterItemName: "无",
      outputQuantity: 3,
    },
    {
      familyId: "insulated_cable",
      displayName: "绝缘线缆",
      description: "重新包覆绝缘层的可用导线。",
      category: "material",
      tags: ["crafting", "electrical"],
      baseCoinCost: 2,
      basePartsCost: 2,
      baseBarterCost: 1,
      barterItemId: "rubber_strip",
      barterItemName: "橡胶条",
      outputQuantity: 3,
    },
    {
      familyId: "fuel_briquette",
      displayName: "燃料块",
      description: "将木屑、石蜡与可燃废料压制成块。",
      category: "material",
      tags: ["crafting", "fuel"],
      baseCoinCost: 1,
      basePartsCost: 1,
      baseBarterCost: 1,
      barterItemId: "paper_bundle",
      barterItemName: "纸束",
      outputQuantity: 3,
    },
    {
      familyId: "salvage_crowbar",
      displayName: "拆解撬棍",
      description: "用于安全拆解门板和机械外壳的基础工具。",
      category: "tool",
      tags: ["tool", "search"],
      baseCoinCost: 3,
      basePartsCost: 4,
      baseBarterCost: 0,
      barterItemId: "none",
      barterItemName: "无",
      outputQuantity: 1,
      modifierTarget: "search.material_quantity",
      modifierPerGrade: 1,
    },
    {
      familyId: "cargo_handcart",
      displayName: "货运手推车",
      description: "以人力拖运的小型陆行载具，适合短途搬运。",
      category: "transport",
      tags: ["transport", "land", "cargo"],
      baseCoinCost: 4,
      basePartsCost: 6,
      baseBarterCost: 1,
      barterItemId: "rubber_strip",
      barterItemName: "橡胶条",
      outputQuantity: 1,
      transportMode: "land",
      modifierTarget: "expedition.carry_capacity",
      modifierPerGrade: 1,
    },
    {
      familyId: "sealed_archive_case",
      displayName: "密封档案箱",
      description: "用于保护报纸、书籍和蓝图免受潮气破坏。",
      category: "archive",
      tags: ["archive", "storage"],
      baseCoinCost: 3,
      basePartsCost: 3,
      baseBarterCost: 1,
      barterItemId: "wax_sheet",
      barterItemName: "防水蜡纸",
      outputQuantity: 1,
      modifierTarget: "archive.protection",
      modifierPerGrade: 2,
    },
  ],
  advancedFamilies: [
    {
      familyId: "field_ration",
      displayName: "行军口粮",
      description: "将谷物、脱水肉与维生素压缩密封的熟食。",
      category: "prepared_food",
      tags: ["food", "prepared", "expedition"],
      baseCoinCost: 5,
      basePartsCost: 2,
      baseBarterCost: 2,
      barterItemId: "dried_meat",
      barterItemName: "脱水肉条",
      outputQuantity: 2,
    },
    {
      familyId: "canned_stew",
      displayName: "罐装炖菜",
      description: "完成杀菌与密封的长期储存熟食。",
      category: "prepared_food",
      tags: ["food", "prepared", "shelter"],
      baseCoinCost: 6,
      basePartsCost: 2,
      baseBarterCost: 2,
      barterItemId: "broth_base",
      barterItemName: "高汤底料",
      outputQuantity: 3,
    },
    {
      familyId: "antiviral_serum",
      displayName: "抗病毒血清",
      description: "根据有限样本制备的干预性血清，无法完全阻断感染。",
      category: "medicine",
      tags: ["medical", "infection"],
      baseCoinCost: 10,
      basePartsCost: 4,
      baseBarterCost: 2,
      barterItemId: "antidote",
      barterItemName: "解毒剂",
      outputQuantity: 1,
    },
    {
      familyId: "trauma_kit",
      displayName: "创伤急救包",
      description: "将止血、固定和抗感染用品按流程组合的医疗套装。",
      category: "medicine",
      tags: ["medical", "healing"],
      baseCoinCost: 8,
      basePartsCost: 4,
      baseBarterCost: 3,
      barterItemId: "medical_supplies",
      barterItemName: "医疗用品",
      outputQuantity: 1,
    },
    {
      familyId: "signal_beacon",
      displayName: "定向信标",
      description: "在尸群间建立短时通信走廊的导航工具。",
      category: "tool",
      tags: ["tool", "signal", "city_unlock"],
      baseCoinCost: 8,
      basePartsCost: 8,
      baseBarterCost: 1,
      barterItemId: "insulated_cable",
      barterItemName: "绝缘线缆",
      outputQuantity: 1,
      modifierTarget: "city_intelligence_gain",
      modifierPerGrade: 1,
    },
    {
      familyId: "field_toolkit",
      displayName: "外勤维修组",
      description: "可在远离避难所时维护武器与载具的工具组。",
      category: "tool",
      tags: ["tool", "repair"],
      baseCoinCost: 7,
      basePartsCost: 9,
      baseBarterCost: 2,
      barterItemId: "fastener_set",
      barterItemName: "紧固件组",
      outputQuantity: 1,
      modifierTarget: "field_repair_efficiency",
      modifierPerGrade: 2,
    },
    {
      familyId: "compound_bow",
      displayName: "复合弓",
      description: "噪声较低、可回收弹药的远程武器。",
      category: "weapon",
      tags: ["weapon", "quiet"],
      baseCoinCost: 8,
      basePartsCost: 12,
      baseBarterCost: 2,
      barterItemId: "insulated_cable",
      barterItemName: "绝缘线缆",
      outputQuantity: 1,
      modifierTarget: "player.attack",
      modifierPerGrade: 2,
    },
    {
      familyId: "pipe_rifle",
      displayName: "管式步枪",
      description: "易于维护的简化远程火器。",
      category: "weapon",
      tags: ["weapon", "firearm"],
      baseCoinCost: 12,
      basePartsCost: 16,
      baseBarterCost: 2,
      barterItemId: "fastener_set",
      barterItemName: "紧固件组",
      outputQuantity: 1,
      modifierTarget: "player.attack",
      modifierPerGrade: 3,
    },
    {
      familyId: "tactical_vest",
      displayName: "战术防护背心",
      description: "在不显著影响活动的前提下保护躯干。",
      category: "armor",
      tags: ["armor", "light"],
      baseCoinCost: 10,
      basePartsCost: 14,
      baseBarterCost: 2,
      barterItemId: "cloth_roll",
      barterItemName: "布卷",
      outputQuantity: 1,
      modifierTarget: "player.defense",
      modifierPerGrade: 2,
    },
    {
      familyId: "hazmat_suit",
      displayName: "气密防护服",
      description: "用于进入强污染建筑的隔离型防护装备。",
      category: "armor",
      tags: ["armor", "infection"],
      baseCoinCost: 12,
      basePartsCost: 15,
      baseBarterCost: 2,
      barterItemId: "rubber_strip",
      barterItemName: "橡胶条",
      outputQuantity: 1,
      modifierTarget: "player.defense",
      modifierPerGrade: 3,
    },
    {
      familyId: "armored_bicycle",
      displayName: "装甲自行车",
      description: "不依赖燃料的安静陆行载具。",
      category: "transport",
      tags: ["transport", "land", "quiet"],
      baseCoinCost: 8,
      basePartsCost: 16,
      baseBarterCost: 2,
      barterItemId: "rubber_strip",
      barterItemName: "橡胶条",
      outputQuantity: 1,
      transportMode: "land",
      modifierTarget: "expedition.range",
      modifierPerGrade: 1,
    },
    {
      familyId: "electric_motorcycle",
      displayName: "电动越野摩托",
      description: "可快速穿过拥堵道路的轻型陆行载具。",
      category: "transport",
      tags: ["transport", "land", "fast"],
      baseCoinCost: 14,
      basePartsCost: 24,
      baseBarterCost: 2,
      barterItemId: "battery_cell",
      barterItemName: "蓄电池组",
      outputQuantity: 1,
      transportMode: "land",
      modifierTarget: "expedition.range",
      modifierPerGrade: 2,
    },
    {
      familyId: "armored_truck",
      displayName: "装甲卡车",
      description: "可承担跨城人员与物资运送的重型载具。",
      category: "transport",
      tags: ["transport", "land", "cargo"],
      baseCoinCost: 24,
      basePartsCost: 38,
      baseBarterCost: 3,
      barterItemId: "fuel_drum",
      barterItemName: "燃料桶",
      outputQuantity: 1,
      transportMode: "land",
      modifierTarget: "expedition.carry_capacity",
      modifierPerGrade: 3,
    },
    {
      familyId: "rail_service_car",
      displayName: "轨道维修车",
      description: "利用尚可通行的铁路进行大宗运输。",
      category: "transport",
      tags: ["transport", "land", "rail"],
      baseCoinCost: 26,
      basePartsCost: 44,
      baseBarterCost: 3,
      barterItemId: "fuel_drum",
      barterItemName: "燃料桶",
      outputQuantity: 1,
      transportMode: "land",
      modifierTarget: "expedition.carry_capacity",
      modifierPerGrade: 4,
    },
    {
      familyId: "inflatable_boat",
      displayName: "加固充气艇",
      description: "可在河道与浅水湾使用的便携水上载具。",
      category: "transport",
      tags: ["transport", "sea", "river"],
      baseCoinCost: 12,
      basePartsCost: 20,
      baseBarterCost: 2,
      barterItemId: "rubber_strip",
      barterItemName: "橡胶条",
      outputQuantity: 1,
      transportMode: "sea",
      modifierTarget: "expedition.range",
      modifierPerGrade: 1,
    },
    {
      familyId: "motorboat",
      displayName: "浅水机动艇",
      description: "用于河道、海湾和岛屿码头之间运输。",
      category: "transport",
      tags: ["transport", "sea", "motor"],
      baseCoinCost: 20,
      basePartsCost: 32,
      baseBarterCost: 3,
      barterItemId: "fuel_drum",
      barterItemName: "燃料桶",
      outputQuantity: 1,
      transportMode: "sea",
      modifierTarget: "expedition.range",
      modifierPerGrade: 2,
    },
    {
      familyId: "sailing_cutter",
      displayName: "帆装快艇",
      description: "少量依赖燃料的远岸水上载具。",
      category: "transport",
      tags: ["transport", "sea", "coastal"],
      baseCoinCost: 24,
      basePartsCost: 38,
      baseBarterCost: 3,
      barterItemId: "cloth_roll",
      barterItemName: "布卷",
      outputQuantity: 1,
      transportMode: "sea",
      modifierTarget: "expedition.range",
      modifierPerGrade: 3,
    },
    {
      familyId: "autogyro",
      displayName: "自转旋翼机",
      description: "起降距离较短的简化飞行载具。",
      category: "transport",
      tags: ["transport", "air", "short_range"],
      baseCoinCost: 32,
      basePartsCost: 52,
      baseBarterCost: 4,
      barterItemId: "aviation_fuel",
      barterItemName: "航空燃料",
      outputQuantity: 1,
      transportMode: "air",
      modifierTarget: "expedition.range",
      modifierPerGrade: 3,
    },
    {
      familyId: "ultralight_aircraft",
      displayName: "超轻型飞机",
      description: "可越过地面阻断的单发轻型飞行载具。",
      category: "transport",
      tags: ["transport", "air", "recon"],
      baseCoinCost: 40,
      basePartsCost: 64,
      baseBarterCost: 4,
      barterItemId: "aviation_fuel",
      barterItemName: "航空燃料",
      outputQuantity: 1,
      transportMode: "air",
      modifierTarget: "expedition.range",
      modifierPerGrade: 4,
    },
    {
      familyId: "utility_helicopter",
      displayName: "通用直升机",
      description: "能够进入岛屿与封锁城区的稀有飞行载具。",
      category: "transport",
      tags: ["transport", "air", "island"],
      baseCoinCost: 55,
      basePartsCost: 80,
      baseBarterCost: 5,
      barterItemId: "rotor_bearing",
      barterItemName: "旋翼轴承",
      outputQuantity: 1,
      transportMode: "air",
      modifierTarget: "expedition.range",
      modifierPerGrade: 5,
    },
  ],
} as const satisfies ManufacturingGenerationConfig;
