import type {
  ContentExpansionThresholds,
  ExpansionDifficultyConfig,
  ExpansionOriginConfig,
  ExpansionTraitConfig,
  FailureEndingConfig,
  ShelterArchetypeConfig,
  TraitSelectionRulesConfig,
} from "./types";

/** 扩展内容必须满足的数量门槛。 */
export const CONTENT_EXPANSION_THRESHOLDS = {
  minimumBasicRecipes: 200,
  minimumAdvancedRecipes: 200,
  requiredTraitCount: 20,
  maximumSelectedTraits: 2,
  requiredOriginCount: 10,
  requiredShelterTypeCount: 10,
  requiredFailureEndingCount: 8,
  minimumTransportItems: 100,
  minimumRawFoodItems: 60,
  minimumSemiFinishedFoodItems: 60,
} as const satisfies ContentExpansionThresholds;

/** 开局特性支持选择一至两个不重复特性。 */
export const TRAIT_SELECTION_RULES = {
  minimumSelections: 1,
  maximumSelections: CONTENT_EXPANSION_THRESHOLDS.maximumSelectedTraits,
  requireUnique: true,
} as const satisfies TraitSelectionRulesConfig;

/** 从新手到永恒梦魇的七档完整难度。 */
export const DIFFICULTY_OPTIONS = [
  {
    difficultyId: "newcomer",
    displayName: "新手",
    description: "适合首次进入《避难所·往昔》：损耗低、敌人弱、物资更多。",
    rank: 1,
    multipliers: {
      survivalCostPercent: 60,
      enemyHealthPercent: 65,
      enemyDamagePercent: 60,
      commonLootPercent: 165,
      textLootPercent: 180,
      researchCostPercent: 70,
      tradePricePercent: 80,
      hopeLossPercent: 50,
    },
    startingModifiers: [
      { target: "player.food", operation: "add", amount: 30, description: "初始食物 +30。" },
      { target: "player.medical_supplies", operation: "add", amount: 20, description: "初始医疗用品 +20。" },
      { target: "shelter.hope", operation: "add", amount: 20, description: "初始希望 +20。" },
    ],
  },
  {
    difficultyId: "watchkeeper",
    displayName: "守望",
    description: "稳定的容错档位，保留完整系统压力但给予较多调整空间。",
    rank: 2,
    multipliers: {
      survivalCostPercent: 80,
      enemyHealthPercent: 85,
      enemyDamagePercent: 80,
      commonLootPercent: 130,
      textLootPercent: 145,
      researchCostPercent: 85,
      tradePricePercent: 90,
      hopeLossPercent: 75,
    },
    startingModifiers: [
      { target: "player.food", operation: "add", amount: 15, description: "初始食物 +15。" },
      { target: "shelter.outer_wall_health", operation: "add", amount: 50, description: "初始外墙耐久 +50。" },
    ],
  },
  {
    difficultyId: "survivor",
    displayName: "求生者",
    description: "标准档位，所有损耗、战斗、掉落与经济使用基准数值。",
    rank: 3,
    multipliers: {
      survivalCostPercent: 100,
      enemyHealthPercent: 100,
      enemyDamagePercent: 100,
      commonLootPercent: 100,
      textLootPercent: 120,
      researchCostPercent: 100,
      tradePricePercent: 100,
      hopeLossPercent: 100,
    },
    startingModifiers: [],
  },
  {
    difficultyId: "desolation",
    displayName: "荒芜",
    description: "城市物资开始枯竭，敌人与经济压力同时上升。",
    rank: 4,
    multipliers: {
      survivalCostPercent: 115,
      enemyHealthPercent: 120,
      enemyDamagePercent: 115,
      commonLootPercent: 82,
      textLootPercent: 110,
      researchCostPercent: 115,
      tradePricePercent: 115,
      hopeLossPercent: 120,
    },
    startingModifiers: [
      { target: "player.food", operation: "subtract", amount: 4, description: "初始食物 -4。" },
      { target: "shelter.hope", operation: "subtract", amount: 8, description: "初始希望 -8。" },
    ],
  },
  {
    difficultyId: "ash_nightmare",
    displayName: "余烬噩梦",
    description: "余烬中的尸群开始有组织地试探防线，每次决策都要付出更高代价。",
    rank: 5,
    multipliers: {
      survivalCostPercent: 135,
      enemyHealthPercent: 145,
      enemyDamagePercent: 140,
      commonLootPercent: 68,
      textLootPercent: 100,
      researchCostPercent: 135,
      tradePricePercent: 130,
      hopeLossPercent: 145,
    },
    startingModifiers: [
      { target: "player.medical_supplies", operation: "subtract", amount: 8, description: "初始医疗用品 -8。" },
      { target: "shelter.outer_wall_health", operation: "subtract", amount: 60, description: "初始外墙耐久 -60。" },
    ],
  },
  {
    difficultyId: "abyssal_siege",
    displayName: "深渊围城",
    description: "稀缺、强敌与快速崩塌的希望同时逼近避难所。",
    rank: 6,
    multipliers: {
      survivalCostPercent: 165,
      enemyHealthPercent: 180,
      enemyDamagePercent: 175,
      commonLootPercent: 52,
      textLootPercent: 90,
      researchCostPercent: 160,
      tradePricePercent: 150,
      hopeLossPercent: 180,
    },
    startingModifiers: [
      { target: "player.food", operation: "subtract", amount: 7, description: "初始食物 -7。" },
      { target: "player.parts", operation: "subtract", amount: 6, description: "初始零件 -6。" },
      { target: "shelter.hope", operation: "subtract", amount: 15, description: "初始希望 -15。" },
    ],
  },
  {
    difficultyId: "eternal_nightmare",
    displayName: "永恒梦魇",
    description: "为极限挑战准备：尸群数值翻倍，掉落锐减，研究和交易几乎无法容错。",
    rank: 7,
    multipliers: {
      survivalCostPercent: 200,
      enemyHealthPercent: 230,
      enemyDamagePercent: 220,
      commonLootPercent: 35,
      textLootPercent: 75,
      researchCostPercent: 200,
      tradePricePercent: 180,
      hopeLossPercent: 230,
    },
    startingModifiers: [
      { target: "player.food", operation: "subtract", amount: 9, description: "初始食物 -9。" },
      { target: "player.medical_supplies", operation: "subtract", amount: 15, description: "初始医疗用品 -15。" },
      { target: "shelter.hope", operation: "subtract", amount: 25, description: "初始希望 -25。" },
    ],
  },
] as const satisfies readonly ExpansionDifficultyConfig[];

/** 十个具有明确开局与搜索加成的所长起源。 */
export const ORIGIN_OPTIONS = [
  {
    originId: "old_city_patrol",
    displayName: "旧城巡警",
    description: "熟悉封锁、破门和近距离交火。",
    startingModifiers: [
      { target: "player.attack", operation: "add", amount: 5, description: "攻击 +5。" },
      { target: "player.defense", operation: "add", amount: 3, description: "防御 +3。" },
    ],
    triggeredBonuses: [
      { triggerId: "search_weapon", target: "loot.weapon_parts", minimum: 1, maximum: 6, chancePercent: 35, description: "搜索武器点时 35% 概率额外获得 1~6 件武器零件。" },
    ],
  },
  {
    originId: "emergency_medic",
    displayName: "急诊医生",
    description: "能从混乱的药房中识别仍可使用的药品。",
    startingModifiers: [
      { target: "player.medical_supplies", operation: "add", amount: 12, description: "医疗用品 +12。" },
      { target: "player.intelligence", operation: "add", amount: 8, description: "智力 +8。" },
    ],
    triggeredBonuses: [
      { triggerId: "search_medicine", target: "loot.medical_supplies", minimum: 1, maximum: 12, chancePercent: 45, description: "搜索医疗区时 45% 概率额外获得 1~12 医疗用品。" },
    ],
  },
  {
    originId: "municipal_engineer",
    displayName: "市政工程师",
    description: "熟悉地下管网与承重结构，擅长识别可用零件。",
    startingModifiers: [
      { target: "player.parts", operation: "add", amount: 15, description: "零件 +15。" },
      { target: "shelter.outer_wall_health", operation: "add", amount: 40, description: "外墙耐久 +40。" },
    ],
    triggeredBonuses: [
      { triggerId: "search_parts", target: "loot.parts", minimum: 1, maximum: 20, chancePercent: 100, description: "搜索到零件时，额外增加 1~20 个零件。" },
    ],
  },
  {
    originId: "wilderness_guide",
    displayName: "荒野向导",
    description: "熟悉可食植物、水源和尸群迁徙痕迹。",
    startingModifiers: [
      { target: "player.food", operation: "add", amount: 10, description: "食物 +10。" },
      { target: "player.agility", operation: "add", amount: 3, description: "敏捷 +3。" },
    ],
    triggeredBonuses: [
      { triggerId: "search_raw_food", target: "loot.raw_food", minimum: 2, maximum: 10, chancePercent: 60, description: "野外搜索时 60% 概率额外获得 2~10 份生鲜食材。" },
    ],
  },
  {
    originId: "community_organizer",
    displayName: "社区组织者",
    description: "懂得在恐惧中维持秩序与共同目标。",
    startingModifiers: [
      { target: "shelter.hope", operation: "add", amount: 12, description: "希望 +12。" },
      { target: "shelter.activity", operation: "add", amount: 8, description: "活跃度 +8。" },
    ],
    triggeredBonuses: [
      { triggerId: "complete_activity", target: "shelter.hope", minimum: 2, maximum: 6, chancePercent: 100, description: "完成避难所活动时额外获得 2~6 希望。" },
    ],
  },
  {
    originId: "logistics_dispatcher",
    displayName: "物流调度员",
    description: "熟悉仓储、配载和跨区路线调度。",
    startingModifiers: [
      { target: "expedition.carry_capacity", operation: "add", amount: 6, description: "外勤携带上限 +6。" },
      { target: "player.coins", operation: "add", amount: 10, description: "金币 +10。" },
    ],
    triggeredBonuses: [
      { triggerId: "settlement_delivery", target: "delivery.quantity", minimum: 2, maximum: 8, chancePercent: 50, description: "避难所运输时 50% 概率额外运送 2~8 份物资。" },
    ],
  },
  {
    originId: "radio_operator",
    displayName: "无线电员",
    description: "能从噪声中拆分方位、呼号和旧时间表。",
    startingModifiers: [
      { target: "player.intelligence", operation: "add", amount: 10, description: "智力 +10。" },
      { target: "city.intelligence", operation: "add", amount: 5, description: "初始城市情报 +5。" },
    ],
    triggeredBonuses: [
      { triggerId: "collect_text", target: "city.intelligence", minimum: 1, maximum: 4, chancePercent: 55, description: "收集文本道具时 55% 概率额外获得 1~4 情报。" },
    ],
  },
  {
    originId: "culinary_technician",
    displayName: "食品技师",
    description: "懂得在设备有限时保鲜、发酵和减少损耗。",
    startingModifiers: [
      { target: "crafting.food_output", operation: "multiply_percent", amount: 125, description: "食品制作产量为 125%。" },
      { target: "player.food", operation: "add", amount: 8, description: "食物 +8。" },
    ],
    triggeredBonuses: [
      { triggerId: "craft_semi_finished_food", target: "crafting.bonus_output", minimum: 1, maximum: 4, chancePercent: 65, description: "制作半成品食物时 65% 概率额外产出 1~4 份。" },
    ],
  },
  {
    originId: "vehicle_mechanic",
    displayName: "载具技师",
    description: "曾经维修工程车与船用发动机。",
    startingModifiers: [
      { target: "crafting.transport_parts_cost", operation: "multiply_percent", amount: 80, description: "载具制作零件成本降至 80%。" },
      { target: "player.parts", operation: "add", amount: 10, description: "零件 +10。" },
    ],
    triggeredBonuses: [
      { triggerId: "search_vehicle", target: "loot.parts", minimum: 3, maximum: 15, chancePercent: 70, description: "搜索载具残骸时 70% 概率额外获得 3~15 零件。" },
    ],
  },
  {
    originId: "disaster_archivist",
    displayName: "灾史档案员",
    description: "相信文本比口述更可靠，会优先保护任何可读记录。",
    startingModifiers: [
      { target: "loot.text_drop_chance", operation: "add", amount: 25, description: "文本类道具掉落率 +25 个百分点。" },
      { target: "shelter.newspapers", operation: "add", amount: 3, description: "旧报纸 +3。" },
    ],
    triggeredBonuses: [
      { triggerId: "search_archive", target: "loot.archive", minimum: 1, maximum: 3, chancePercent: 75, description: "搜索档案建筑时 75% 概率额外获得 1~3 份文本。" },
    ],
  },
] as const satisfies readonly ExpansionOriginConfig[];

/** 二十个可任选至多两个的所长特性。 */
export const TRAIT_OPTIONS = [
  {
    traitId: "hot_blooded",
    displayName: "好勇斗狠",
    description: "抢占先手但会暴露防守空档。",
    modifiers: [
      { target: "player.attack", operation: "add", amount: 6, description: "攻击 +6。" },
      { target: "player.defense", operation: "subtract", amount: 2, description: "防御 -2。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: ["calm_under_fire"],
  },
  {
    traitId: "meticulous",
    displayName: "谨慎周密",
    description: "习惯多次复核路线，减少意外但行动更慢。",
    modifiers: [
      { target: "expedition.action_capacity", operation: "subtract", amount: 1, description: "每次外勤可用行动 -1。" },
      { target: "event.negative_chance", operation: "subtract", amount: 15, description: "负面事件几率 -15 个百分点。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: ["risk_taker"],
  },
  {
    traitId: "rallying_voice",
    displayName: "人心所向",
    description: "能在群体动摇时找到一个大家都愿意接受的理由。",
    modifiers: [{ target: "shelter.hope", operation: "add", amount: 15, description: "初始希望 +15。" }],
    triggeredBonuses: [{ triggerId: "weekly_summary", target: "shelter.hope", minimum: 1, maximum: 5, chancePercent: 100, description: "每周总结后希望 +1~5。" }],
    incompatibleTraitIds: [],
  },
  {
    traitId: "scavenger_instinct",
    displayName: "拾荒直觉",
    description: "对废墟中不自然的结构和反光格外敏感。",
    modifiers: [{ target: "loot.material_drop_chance", operation: "add", amount: 18, description: "材料掉落率 +18 个百分点。" }],
    triggeredBonuses: [{ triggerId: "search_material", target: "loot.parts", minimum: 1, maximum: 8, chancePercent: 45, description: "搜索材料时 45% 概率额外获得 1~8 零件。" }],
    incompatibleTraitIds: [],
  },
  {
    traitId: "iron_stomach",
    displayName: "铁胃",
    description: "能适应较粗糙的食物，但不代表可以忽略污染。",
    modifiers: [{ target: "food.hunger_recovery", operation: "multiply_percent", amount: 120, description: "食物恢复效果为 120%。" }],
    triggeredBonuses: [{ triggerId: "eat_raw_food", target: "player.infection_resistance", minimum: 15, maximum: 30, chancePercent: 100, description: "食用生食时额外获得 15~30 感染抗性。" }],
    incompatibleTraitIds: [],
  },
  {
    traitId: "night_owl",
    displayName: "夜行者",
    description: "夜间保持清醒，白天却更容易疲劳。",
    modifiers: [
      { target: "night.search_efficiency", operation: "multiply_percent", amount: 125, description: "夜间搜索效率为 125%。" },
      { target: "day.search_efficiency", operation: "multiply_percent", amount: 90, description: "白天搜索效率为 90%。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: ["early_riser"],
  },
  {
    traitId: "early_riser",
    displayName: "晨光行者",
    description: "善于利用天刚亮时的尸群空隙。",
    modifiers: [
      { target: "day.search_efficiency", operation: "multiply_percent", amount: 118, description: "白天搜索效率为 118%。" },
      { target: "night.search_efficiency", operation: "multiply_percent", amount: 92, description: "夜间搜索效率为 92%。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: ["night_owl"],
  },
  {
    traitId: "field_medic",
    displayName: "战地急救",
    description: "熟悉压迫止血和伤情分级。",
    modifiers: [{ target: "medical.healing", operation: "multiply_percent", amount: 125, description: "医疗恢复效果为 125%。" }],
    triggeredBonuses: [{ triggerId: "use_medical_item", target: "medical.refund", minimum: 1, maximum: 1, chancePercent: 20, description: "使用医疗品时 20% 概率返还 1 份材料。" }],
    incompatibleTraitIds: [],
  },
  {
    traitId: "mechanic_touch",
    displayName: "机械手感",
    description: "通过声音和振动就能判断大多数机械故障。",
    modifiers: [{ target: "repair.parts_cost", operation: "multiply_percent", amount: 85, description: "所有维修零件成本降至 85%。" }],
    triggeredBonuses: [{ triggerId: "repair_transport", target: "player.parts", minimum: 1, maximum: 5, chancePercent: 35, description: "维修载具时 35% 概率回收 1~5 零件。" }],
    incompatibleTraitIds: [],
  },
  {
    traitId: "barter_sense",
    displayName: "物价敏感",
    description: "能迅速判断不同聚落真正缺少什么。",
    modifiers: [
      { target: "trade.buy_price", operation: "multiply_percent", amount: 90, description: "购买价格降至 90%。" },
      { target: "trade.sell_price", operation: "multiply_percent", amount: 112, description: "贩卖价格提高至 112%。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: [],
  },
  {
    traitId: "calm_under_fire",
    displayName: "临危不乱",
    description: "子弹和嚎叫不会打乱呼吸。",
    modifiers: [
      { target: "player.defense", operation: "add", amount: 5, description: "防御 +5。" },
      { target: "combat.critical_chance", operation: "subtract", amount: 5, description: "暴击率 -5 个百分点。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: ["hot_blooded"],
  },
  {
    traitId: "pack_rat",
    displayName: "背包囤积者",
    description: "总能在包中挤出一点新空间，但负重会拖慢脚步。",
    modifiers: [
      { target: "expedition.carry_capacity", operation: "add", amount: 8, description: "外勤携带上限 +8。" },
      { target: "player.agility", operation: "subtract", amount: 2, description: "敏捷 -2。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: ["light_footed"],
  },
  {
    traitId: "light_footed",
    displayName: "轻装潜行",
    description: "优先避开石子、碎玻璃和会发出声音的金属。",
    modifiers: [
      { target: "player.agility", operation: "add", amount: 5, description: "敏捷 +5。" },
      { target: "expedition.carry_capacity", operation: "subtract", amount: 4, description: "外勤携带上限 -4。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: ["pack_rat"],
  },
  {
    traitId: "hard_laborer",
    displayName: "耐久劳作",
    description: "长时间体力劳动已经成为习惯。",
    modifiers: [
      { target: "job.output", operation: "multiply_percent", amount: 125, description: "工作产出为 125%。" },
      { target: "job.hunger_cost", operation: "multiply_percent", amount: 110, description: "工作饥饿损耗为 110%。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: [],
  },
  {
    traitId: "bookworm",
    displayName: "旧书虫",
    description: "能快速判断一份旧资料是否值得保留。",
    modifiers: [
      { target: "research.duration", operation: "multiply_percent", amount: 85, description: "研究时长降至 85%。" },
      { target: "loot.text_drop_chance", operation: "add", amount: 12, description: "文本掉落率 +12 个百分点。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: [],
  },
  {
    traitId: "river_rat",
    displayName: "河道子民",
    description: "熟悉潮汐、浅滩与废弃码头的水流。",
    modifiers: [
      { target: "sea_transport.range", operation: "multiply_percent", amount: 125, description: "水上载具航程为 125%。" },
      { target: "search.fish_quantity", operation: "add", amount: 2, description: "水域搜索的鱼类数量 +2。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: [],
  },
  {
    traitId: "aviator",
    displayName: "低空飞手",
    description: "还记得气流、载重和紧急迫降的处理方式。",
    modifiers: [
      { target: "air_transport.range", operation: "multiply_percent", amount: 130, description: "飞行载具航程为 130%。" },
      { target: "air_transport.failure_chance", operation: "subtract", amount: 20, description: "飞行事故概率 -20 个百分点。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: [],
  },
  {
    traitId: "gardener",
    displayName: "灰土园丁",
    description: "懂得在缺光、缺水和污染土壤中保住作物。",
    modifiers: [{ target: "facility.greenhouse_output", operation: "multiply_percent", amount: 135, description: "温室食物产出为 135%。" }],
    triggeredBonuses: [{ triggerId: "weekly_greenhouse", target: "loot.raw_food", minimum: 2, maximum: 7, chancePercent: 100, description: "每周温室额外产出 2~7 份生鲜食材。" }],
    incompatibleTraitIds: [],
  },
  {
    traitId: "loyal_guard",
    displayName: "护伴心切",
    description: "不会把同伴留在尸群后面。",
    modifiers: [
      { target: "companion.damage_received", operation: "multiply_percent", amount: 85, description: "角色受到伤害降至 85%。" },
      { target: "player.damage_received", operation: "multiply_percent", amount: 108, description: "所长受到伤害增至 108%。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: [],
  },
  {
    traitId: "risk_taker",
    displayName: "险中求生",
    description: "愿意用更高的代价换取更大的战利品可能。",
    modifiers: [
      { target: "loot.quantity", operation: "multiply_percent", amount: 130, description: "搜索收益为 130%。" },
      { target: "event.negative_chance", operation: "add", amount: 20, description: "负面事件几率 +20 个百分点。" },
    ],
    triggeredBonuses: [],
    incompatibleTraitIds: ["meticulous"],
  },
] as const satisfies readonly ExpansionTraitConfig[];

/** 十种可建立主避难所的初始建筑类型。 */
export const SHELTER_TYPES = [
  {
    id: "air_raid_bunker",
    label: "防空洞避难所",
    description: "传统民防工事，内墙稳固但扩建空间有限。",
    bonuses: ["内墙耐久 +120", "受到轰击伤害 -15%"],
    starting_capacity: 18,
    initialFacilitySlots: 5,
    innerWallHealth: 520,
    outerWallHealth: 260,
    allowedTerrain: ["land", "underground"],
    modifiers: [{ target: "shelter.blast_damage", operation: "multiply_percent", amount: 85, description: "轰击伤害降至 85%。" }],
  },
  {
    id: "subway_station",
    label: "地铁站避难所",
    description: "通道丰富且便于外出，多个出入口使外墙巡逻更困难。",
    bonuses: ["陆行外勤时长 -10%", "起始人口容量 +8"],
    starting_capacity: 28,
    initialFacilitySlots: 6,
    innerWallHealth: 410,
    outerWallHealth: 210,
    allowedTerrain: ["land", "underground"],
    modifiers: [{ target: "land_expedition.duration", operation: "multiply_percent", amount: 90, description: "陆行外勤时长降至 90%。" }],
  },
  {
    id: "underground_garage",
    label: "地下车库避难所",
    description: "载具维修空间宽阔，但通风和防水较差。",
    bonuses: ["载具制造成本 -15%", "初始设施槽 +1"],
    starting_capacity: 24,
    initialFacilitySlots: 7,
    innerWallHealth: 360,
    outerWallHealth: 280,
    allowedTerrain: ["land", "underground"],
    modifiers: [{ target: "crafting.transport_cost", operation: "multiply_percent", amount: 85, description: "载具制造成本降至 85%。" }],
  },
  {
    id: "abandoned_missile_silo",
    label: "废弃导弹井避难所",
    description: "极深、坚固且容易隐蔽，地表出口是唯一的脆弱点。",
    bonuses: ["内墙耐久 +200", "高级研究时长 -10%"],
    starting_capacity: 20,
    initialFacilitySlots: 5,
    innerWallHealth: 650,
    outerWallHealth: 180,
    allowedTerrain: ["land", "underground"],
    modifiers: [{ target: "research.advanced_duration", operation: "multiply_percent", amount: 90, description: "高级研究时长降至 90%。" }],
  },
  {
    id: "civil_defense_tunnel",
    label: "人防隧道避难所",
    description: "狭长且易于分区封闭，适合将污染隔绝在局部。",
    bonuses: ["感染扩散率 -25%", "内墙维护零件 -10%"],
    starting_capacity: 22,
    initialFacilitySlots: 6,
    innerWallHealth: 480,
    outerWallHealth: 230,
    allowedTerrain: ["land", "underground"],
    modifiers: [{ target: "infection.spread", operation: "multiply_percent", amount: 75, description: "感染扩散率降至 75%。" }],
  },
  {
    id: "hospital_basement",
    label: "医院地库避难所",
    description: "保留了部分医疗管线和隔离间，也更接近早期感染源。",
    bonuses: ["治疗效果 +20%", "医疗制作产量 +1"],
    starting_capacity: 20,
    initialFacilitySlots: 6,
    innerWallHealth: 380,
    outerWallHealth: 220,
    allowedTerrain: ["land", "underground"],
    modifiers: [{ target: "medical.healing", operation: "multiply_percent", amount: 120, description: "治疗效果提高至 120%。" }],
  },
  {
    id: "mountain_cavern",
    label: "山体洞库避难所",
    description: "远离城区尸潮且稳定，但对外运输路线狭窄。",
    bonuses: ["尸潮强度 -20%", "城市运输时长 +15%"],
    starting_capacity: 26,
    initialFacilitySlots: 5,
    innerWallHealth: 560,
    outerWallHealth: 320,
    allowedTerrain: ["land", "underground"],
    modifiers: [{ target: "horde.strength", operation: "multiply_percent", amount: 80, description: "尸潮强度降至 80%。" }],
  },
  {
    id: "factory_shelter",
    label: "废弃工厂避难所",
    description: "车间可快速改造为制造区，广阔外围需要更多巡逻人员。",
    bonuses: ["制造时长 -15%", "初始设施槽 +2"],
    starting_capacity: 32,
    initialFacilitySlots: 8,
    innerWallHealth: 340,
    outerWallHealth: 360,
    allowedTerrain: ["land"],
    modifiers: [{ target: "crafting.duration", operation: "multiply_percent", amount: 85, description: "制造时长降至 85%。" }],
  },
  {
    id: "reservoir_service_tunnel",
    label: "水库维修道避难所",
    description: "接近水源与封闭管廊，洪水是需要持续监测的风险。",
    bonuses: ["净化水产量 +35%", "水上载具研究成本 -10%"],
    starting_capacity: 19,
    initialFacilitySlots: 6,
    innerWallHealth: 420,
    outerWallHealth: 240,
    allowedTerrain: ["sea", "underground"],
    modifiers: [{ target: "facility.water_output", operation: "multiply_percent", amount: 135, description: "净水产量提高至 135%。" }],
  },
  {
    id: "coastal_fort",
    label: "海防要塞避难所",
    description: "拥有对海观测和厚重外墙，潮气会加速金属设施损耗。",
    bonuses: ["外墙耐久 +140", "水上外勤航程 +20%"],
    starting_capacity: 25,
    initialFacilitySlots: 7,
    innerWallHealth: 430,
    outerWallHealth: 500,
    allowedTerrain: ["sea", "land"],
    modifiers: [{ target: "sea_transport.range", operation: "multiply_percent", amount: 120, description: "水上载具航程提高至 120%。" }],
  },
] as const satisfies readonly ShelterArchetypeConfig[];

/** 八个互不重复且具有结算优先级的失败结局。 */
export const FAILURE_ENDINGS = [
  {
    endingId: "outer_wall_overrun",
    displayName: "潮水越墙",
    triggerId: "outer_wall_health_zero",
    priority: 80,
    summary: "外墙失守，尸潮在巡逻队完成下一次修补前涌入。",
    epilogue: "最后一盏巡逻灯在清晨熄灭，再没有人回答墙内的呼叫。",
  },
  {
    endingId: "inner_wall_collapse",
    displayName: "心墙崩塌",
    triggerId: "inner_wall_health_zero",
    priority: 90,
    summary: "长期失修使内墙在一次振动中倒塌，生活区失去最后隔离。",
    epilogue: "灰尘散尽时，曾经记录每个人名字的白板被埋在瓦砾下。",
  },
  {
    endingId: "hope_extinguished",
    displayName: "无人守望",
    triggerId: "hope_zero",
    priority: 60,
    summary: "希望归零，幸存者不再相信明天值得等待。",
    epilogue: "门被从内部打开。人们各自走入雨里，连争吵都已经显得多余。",
  },
  {
    endingId: "famine_riot",
    displayName: "空碗之夜",
    triggerId: "group_hunger_limit",
    priority: 70,
    summary: "群体饥饿超过临界值，仓库在一夜之间变成战场。",
    epilogue: "第二天没有人敲响吃饭的铃；锅里只剩下一层被刮花的金属。",
  },
  {
    endingId: "infection_bloom",
    displayName: "内部花开",
    triggerId: "infection_pressure_limit",
    priority: 100,
    summary: "隐瞒的感染在封闭房间内同时发作。",
    epilogue: "通讯器里最后的声音是一句迟到的道歉，然后是漫长的撞门声。",
  },
  {
    endingId: "commander_fallen",
    displayName: "所长的空椅",
    triggerId: "all_commanders_dead",
    priority: 95,
    summary: "最后一位所长在战斗、伤势或寿命终点中倒下。",
    epilogue: "指挥室的椅子被推回桌下，却再没有人愿意坐上去。",
  },
  {
    endingId: "settlement_schism",
    displayName: "裂成两岸",
    triggerId: "activity_minimum",
    priority: 50,
    summary: "活跃度跌至下限，无人再愿维持共同的秩序。",
    epilogue: "两支队伍带着各自的火种离开，谁都没有回头看那块共同立起的招牌。",
  },
  {
    endingId: "lost_exodus",
    displayName: "没有回程",
    triggerId: "activity_maximum",
    priority: 85,
    summary: "活跃度突破上限，狂热的人群擅自组织车队转移，随后全员失联。",
    epilogue: "旧避难所与新目的地同时保持沉默，地图上只剩一条没画完的线。",
  },
] as const satisfies readonly FailureEndingConfig[];
